{{- if eq .Values.osm.trafficInterceptionMode "ebpf" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: osm-interceptor
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
    app: osm-interceptor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osm-interceptor
  labels:
    {{- include "osm.labels" . | nindent 4 }}
    app: osm-interceptor
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: osm-interceptor
  labels:
    {{- include "osm.labels" . | nindent 4 }}
    app: osm-interceptor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: osm-interceptor
subjects:
- kind: ServiceAccount
  name: osm-interceptor
  namespace: osm-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: osm-interceptor
  namespace: {{ include "osm.namespace" . }}
  labels:
    {{- include "osm.labels" . | nindent 4 }}
    app: osm-interceptor
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: osm-interceptor
  template:
    metadata:
      labels:
        app: osm-interceptor
    spec:
      hostNetwork: true
      containers:
      - image: "localhost:5000/flomesh/osm-edge-interceptor:latest"
        imagePullPolicy: Always
        name: osm-interceptor
        args:
        - /app/mbctl
        - -m
        - osm
        - --use-reconnect=true
        - --cni-mode=false
        lifecycle:
          preStop:
            exec:
              command:
              - make
              - -k
              - clean
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 200Mi
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /sys/fs/cgroup
            name: sys-fs-cgroup
          - mountPath: /host/opt/cni/bin
            name: cni-bin-dir
          - mountPath: /host/etc/cni/net.d
            name: cni-config-dir
          - mountPath: /host/proc
            name: host-proc
          - mountPath: /host/var/run
            name: host-var-run
            mountPropagation: Bidirectional
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccount: osm-interceptor
      serviceAccountName: osm-interceptor
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
      - hostPath:
          path: /sys/fs/cgroup
        name: sys-fs-cgroup
      - hostPath:
          path: /proc
        name: host-proc
      - hostPath:
          path: /opt/cni/bin
        name: cni-bin-dir
      - hostPath:
          path: /etc/cni/net.d
        name: cni-config-dir
      - hostPath:
          path: /var/run
        name: host-var-run
{{- end }}