ARG DOCKER_REGISTRY
ARG UBUNTU_VERSION

FROM $DOCKER_REGISTRY/ubuntu:$UBUNTU_VERSION as rootfs
RUN apt-get update && \
apt-get upgrade -y && \
apt-get purge --auto-remove && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

FROM scratch
LABEL maintainer="flomesh.io"
LABEL repository="https://github.com/flomesh-io/osm-edge/tree/depend-images"
COPY --from=rootfs / /