name: Nightly Images
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  images:
    name: Docker Images
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.RELEASE_DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.RELEASE_DOCKER_PASS }}
      CTR_TAG: latest-nightly
      CTR_REGISTRY: flomesh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username "$DOCKER_USER" --password-stdin <<< "$DOCKER_PASS"
      - name: Push images with "latest-nightly" tag
        run: make docker-build-cross
