name: Release Helm Chart
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  version:
    name: Set Version from git ref
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        run: echo "::set-output name=version::$(sed 's#^refs/tags/\(.*\)#\1#' <<< '${{ github.ref }}' | cut -c 2-)"

  release:
    runs-on: ubuntu-latest
    needs: version
    env:
      VERSION: ${{ needs.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          app_version: ${{ env.VERSION }}
          chart_version: ${{ env.VERSION }}
